export const plugins = [
  "print",
  "preview",
  "searchreplace",
  "autolink",
  "directionality",
  "visualblocks",
  "visualchars",
  "fullscreen",
  "image",
  "link",
  "media",
  "template",
  "code",
  "codesample",
  "table",
  "charmap",
  "hr",
  "pagebreak",
  "nonbreaking",
  "anchor",
  "insertdatetime",
  "advlist",
  "lists",
  "wordcount",
  "imagetools",
  "textpattern",
  "help",
  "emoticons",
  "autosave",
  "autoresize",
  "formatpainter",
  "toc",
  "tabfocus"
];
export const toolbar = [
  "code",
  "undo",
  "redo",
  "restoredraft",
  "|",
  "cut",
  "copy",
  "paste",
  "pastetext",
  "|",
  "forecolor",
  "backcolor",
  "bold",
  "italic",
  "underline",
  "strikethrough",
  "link",
  "anchor",
  "|",
  "alignleft",
  "aligncenter",
  "alignright",
  "alignjustify",
  "outdent",
  "indent",
  "toc",
  "|",
  "styleselect",
  "formatselect",
  "fontselect",
  "fontsizeselect",
  "|",
  "bullist",
  "numlist",
  "|",
  "blockquote",
  "subscript",
  "superscript",
  "removeformat",
  "|",
  "table",
  "image",
  "media",
  "charmap",
  "emoticons",
  "hr",
  "pagebreak",
  "insertdatetime",
  "print",
  "preview",
  "lineheight",
  "formatpainter",
  "wordcount",
  "template",
  "searchreplace",
  "nonbreaking",
  "|",
  "fullscreen",
];

export const fontsizeFormats = [
  "12px",
  "14px",
  "16px",
  "18px",
  "24px",
  "36px",
  "48px",
  "56px",
  "72px"
];

export const fontFormats = [
  "微软雅黑=Microsoft YaHei,Helvetica Neue,PingFang SC,sans-serif",
  "苹果苹方=PingFang SC,Microsoft YaHei,sans-serif",
  "宋体=simsun,serif",
  "仿宋体=FangSong,serif",
  "黑体=SimHei,sans-serif",
  "Arial=arial,helvetica,sans-serif",
  "Arial Black=arial black,avant garde",
  "Book Antiqua=book antiqua,palatino",
];

export const language = 'zh_CN';
export const contextmenu = ['bold', 'copy', 'link'];
export const templates = [
  {title: 'Some title 1', description: 'Some desc 1', content: 'My content'},
];